### ISSUE TITLE
rename rpm-md to rpm for type

### ISSUE THREAD

**Issue by ausil** [openSUSE/zypper#100]
rpm-md is not a real type and seems to make no sense at all. the type should be rpm, I looked to find discussions on why the chosen name was chosen but was unable to do so.

**Comment by Conan-Kudo** [comment]
Type 'rpm' was reserved for apt-rpm metadata (which, admittedly, zypper doesn't support). The original name for 'rpm-md' was 'repomd' (after the repomd.xml file), and before that, it was known as the yum metadata format. apt-rpm still calls it 'repomd', while smart calls it 'rpm-md' like Zypper does.

Unfortunately, all the information about the name change to 'rpm-md' disappeared with the loss of the Duke University pages on the format.

**Comment by mlandres** [comment]
Thanks for the summary. By now I see no need to rename it.

**Comment by Conan-Kudo** [comment]
@mlandres To be fair, nothing actually supports apt-rpm metadata except apt-rpm, and the type 'rpm' would probably be well-understood to equal 'rpm-md'. It could be added as an alias, like 'yum' and 'repomd' are for 'rpm-md'. If Zypper were to ever add support for apt-rpm metadata, it'd probably be called 'apt-rpm' anyway.

**Comment by mlandres** [comment]
I could allow this as an alias, but zypper output (especially XML) will continue to use rpm-md.

**Comment by Conan-Kudo** [comment]
@mlandres I don't think that's a problem.
