### ISSUE TITLE
Unexpected order of installation

### ISSUE THREAD

**Issue by devalru** [openSUSE/zypper#102]
Hi, 

I am using SLES12 with rpm 4.4.2 and zypper 1.12.40

My rpm package (built with the gradle rpm nebula plugin) defines the INFO/REQUIRES list

packageZ
packageX
packageY

with needed package dependencies.

My problem: zypper solves and installs the packages in lexicographic order

packageX
packageY
packageZ

Is it possible to guarantee the order of installation of dependencies like it is defined in REQUIRES ?
Thank you very much for help.

**Comment by mlandres** [comment]
No (assume a second package defining the same requirements in reverse order - who should rule?).
Zypper will always try to install a package after its requirements got installed. If `Y requires X` and `X requires Z` the order is likely to be ' Z X Y'. But it's not a guarantee.
