### ISSUE TITLE
Is zypper-aptitude really essential on update?

### ISSUE THREAD

**Issue by colbec** [openSUSE/zypper#106]
openSUSE Leap 42.2 does not seem to like that I prefer not to have zypper-aptitude installed. In my experience having a package that tries to respond to `apt-get` just confuses things. So I remove it from my system. But then on update of zypper the update process really wants it to be there, so I allow it to install again, and then once the process is finished just delete it again; and there is no problem with this. Is there a setting somewhere in the zypper update procedure that thinks zypper-aptitude is an essential component in error?

**Comment by jreidinger** [comment]
@colbec it is probably caused by some dependency that recommends this package. If you do not want it again, just lock it after installation with `zypper al`

**Comment by colbec** [comment]
@jreidinger Thanks, but I'm not persuaded that locking `zypper` just to prevent installation of `zypper-aptitude` is to my advantage assuming that updates to `zypper` bring more advantages than disadvantages. I did have a look for a package that really wants `zypper-aptitude` or the `apt-get `access that it provides, but was not successful. I guess my best option right now is to let it install and then delete.

**Comment by jreidinger** [comment]
@colbec no, I mean lock zypper-aptitude, so it should not be installed by update. simple `zypper al zypper-aptitude` after you uninstall it and it should not be installed again.

**Comment by colbec** [comment]
@jreidinger Aha! thanks for that, I did not realize I could lock applications out as well as in place. That's helpful. Done and done.
