### ISSUE TITLE
Zypper becomes very slow when many locks are used

### ISSUE THREAD

**Issue by paulatz** [openSUSE/zypper#107]
Hello,
for some reason I do not want automatic updates to keep installing the  texlive-*-doc packages that come with opensuse (tumbleweed), yet I want to use the texlive packages, which recommend them.

To do this I manually removed the texlive-*-doc packages (ther where 662 of them installed) and locked them with zypper. To set the locks I just used:
zypper al $listofpackages
where $listofpackages is a list of 660 packages names. This command added 660 locks.

After setting this lock, I noticed that zypper operations became much slower. In particular the initial phase of "update" and "distro-update".

I then removed the locks and added a single lock
zypper al texlive-*-doc
which adds a single lock with a glob expression, and does not cause any performance issue. Note that this locks all the 2700+ doc packages, not just the 660 that were originally installed, which is a plus for me.

**Comment by mlandres** [comment]
Basically each lock pattern resolves to a query. Evaluating a query is far slower than processing the matches. That's why less locks are faster even if they produce more matches.
