### ISSUE TITLE
shortcuts in English like in the German bugfix

### ISSUE THREAD

**Issue by skriesch** [openSUSE/zypper#114]
Last year I had a bug for adding German shortcuts in the German translation: https://bugzilla.opensuse.org/show_bug.cgi?id=975794
I added that. The problem is that Weblate shows that as a mistake.

#: src/callbacks/keyring.h:235
msgid "Don't trust the key."
msgstr "Den Schlüssel abweisen. (a)"

#. translators: help text for the 't' option in the 'r/t/a' prompt
#: src/callbacks/keyring.h:237
msgid "Trust the key temporarily."
msgstr "Dem Schlüssel temporär vertrauen. (t)"

#. translators: help text for the 'a' option in the 'r/t/a' prompt
#: src/callbacks/keyring.h:240
msgid "Trust the key and import it into trusted keyring."
msgstr ""
"Dem Schlüssel immer vertrauen und in den vertrauenswürdigen Schlüsselbund "
"importieren. (i)"

Can you add English shortcuts in brackets, too? That would be excellent!
Thanks!

**Comment by mlandres** [comment]
```
Wollen Sie den Schlüssel abweisen, ihm temporär oder immer vertrauen? [a/t/i/? zeigt alle Optionen] (a): ?

a - Den Schlüssel abweisen. (a)
t - Dem Schlüssel temporär vertrauen. (t)
i - Dem Schlüssel immer vertrauen und in den vertrauenswürdigen Schlüsselbund importieren. (i)
```

IMO the shortcuts in brackets are not necessary, because zypper already displays shortcut and helptext.

**Comment by skriesch** [comment]
Should I remove them again? That was part of the bugfix, because people didn't understand the shortcuts...
We have to use the same structure in English and German.

**Comment by mlandres** [comment]
I think the original problem was not located in the option help texts, but in the question. The question has been translated, but not the shortcuts:
```
Do you want to reject the key, trust temporarily, or trust always?    [r/t/a/?]
Wollen Sie den Schlüssel abweisen, ihm temporär oder immer vertrauen? [r/t/a/?]
```
This was fixed by translating the shortcuts as well:
```
Do you want to reject the key, trust temporarily, or trust always?    [r/t/a/?]
Wollen Sie den Schlüssel abweisen, ihm temporär oder immer vertrauen? [a/t/i/?]
```
Repeating the shortcut in the option help text is not necessary, as zypper prepends it. So I would remove them.

**Comment by skriesch** [comment]
I removed it now. The fix for this issue will arrive in some minutes via Weblate and "Sarah Kriesch".

**Comment by mlandres** [comment]
Danke!
