### ISSUE TITLE
Do not require sudo for `zypper in --dry-run`

### ISSUE THREAD

**Issue by boombatower** [openSUSE/zypper#115]
steamtricks tries to auto install all needed dependencies of steam games using [`zypper in -C`](
https://github.com/steamtricks/steamtricks/blob/master/src/steamtricks#L320), but unfortunately there is no method for detecting if these capabilities are already installed. Something like `zypper se` does not allow searching for capabilities (this could be another solution). The end result is that steamtricks has to prompt for sudo whenever the dependency list has changed even if all capabilities are already installed or not available. This is clearly suboptimal.

It would seem more then reasonable for `zypper in --dry-run` to not require sudo at which points steamtricks could run to check for anything to install and only then prompt the user.

Alternatively, the whole install everything the binaries need functionality (lines above the link) could be merged into zypper itself. Using rpm's existing tools the script determines everything the binaries in a game directory require and excludes what they already provide to come up with a list of capabilities they require. Basically a sudo package build. Something I have considered is turning this list of requires/provides into meta packages that can be properly installed to allow for `zypper rm -u` cleanup and similar, but it is a bit of work to generate the packages locally and setup repo.

The end result is one can install all requirements by pointing at a binary/directory which seems like a rather handy feature for zypper.

Anyway, the primary objective seems simple enough, and I'll likely look into it eventually if no one else does. I'd imagine it would be fairly simple for someone already familiar with zypper.

**Comment by mlandres** [comment]
What about `zypper se -i -x --provides <some_capability>` ?

'--dry-run' does not install, but performs a repo refresh before computing the transaction. That's why sudo is needed. I don't think we'll change this.
