### ISSUE TITLE
Repeated questions on Fedora broken repos

### ISSUE THREAD

**Issue by jayvdb** [openSUSE/zypper#120]
I have a few broken copr repos, which dnf kindly warns about but otherwise skips, but zypper asks me how I want to proceed, but it asks twice.

```
File '/repodata/repomd.xml' not found on medium 'https://copr-be.cloud.fedoraproject.org/results/jonludlam/opam/fedora-rawhide-x86_64/'

Abort, retry, ignore? [a/r/i/...? shows all options] (a): i
Abort, retry, ignore? [a/r/i/...? shows all options] (a): i
Error building the cache:
[jonludlam-opam|https://copr-be.cloud.fedoraproject.org/results/jonludlam/opam/fedora-rawhide-x86_64/] Valid metadata not found at specified URL
Warning: Skipping repository 'Copr repo for opam owned by jonludlam' because of the above error.
```

(this occurs on the [zypper 1.13.28](https://apps.fedoraproject.org/packages/zypper) packaged with Fedora, and also on a clean build of master libsolv, libzypp and zypper (after more fiddling that should be necessary..more issues yet to be raised) )

**Comment by bzeller** [comment]
We fixed a similar bug to this a while ago, please reopen if its still a issue.
