### ISSUE TITLE
zypper does not always find pattern devel_C_C++ with --match_exact

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#124]
Michael Karcher reports in boo#556664

Variant 1: devel_C_C++ is the only package queried (OK):

```
# zypper se -t pattern --match-exact 'devel_C_C++'
S | Name        | Summary           | Type
--+-------------+-------------------+--------
  | devel_C_C++ | C/C++ Development | pattern
```

Variant 2: devel_C_C++ queried together with another package(NOT FOUND!):

```
# zypper se -t pattern --match-exact devel_C_C++ enhanced_base
S | Name          | Summary              | Type
--+---------------+----------------------+--------
i | enhanced_base | Enhanced Base System | pattern
```

Variant 3: Like 2, but with another package not having pluses in the name:

```
# zypper se -t pattern --match-exact devel_perl enhanced_base
S | Name          | Summary              | Type
--+---------------+----------------------+--------
i | devel_perl    | Perl Development     | pattern
i | enhanced_base | Enhanced Base System | pattern
```

Problem with pattern matching?

Reproducible: Always

Steps to Reproduce:
Run the commands given in "Details".

Expected Results:  
Should have found devel_C_C++...

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
