### ISSUE TITLE
zypper emits confusing error message when repository needs to be refreshed

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#125]
Federico Mena Quintero writes in https://bugzilla.opensuse.org/show_bug.cgi?id=387874 (and I have hit this bug several times myself, so I believe it is still present):

If you do "zypper addrepo <url> <name>", the repo is created with auto-refresh turned off by default.

Later, if you do "zypper install somepackage", it may be that your cache has info about an old version of the package, which is no longer available in the repository.

In this case, zypper gives you an unhelpful error message:

```
| Downloading package yast2-dns-server-2.16.3-12.noarch, 142.0 K (912.0 K unpacked)
| Media source 'http://download.opensuse.org/distribution/SL-OSS-factory/inst-source' does not contain the desired medium
| 
| Abort, retry, ignore? [A/r/i]: r
```

At this point, I'm thinking, "is the remote repository screwed up?  Is it going to a mirror and the mirror is screwed up?".  After hitting Retry, I get this:

```
| * Downloading: yast2-dns-server-2.16.3-12.noarch.rpm [done]
File './suse/noarch/yast2-dns-server-2.16.3-12.noarch.rpm' not found on medium 'http://download.opensuse.org/distribution/SL-OSS-factory/inst-source'
| 
| Abort, retry, ignore? [A/r/i]: a
| * Downloading: content [done]
| Problem downloading the package file from the repository:
| Can't provide ./suse/noarch/yast2-dns-server-2.16.3-12.noarch.rpm : Media Exception
| Repository 'Factory OSS' is out of date. Running 'zypper refresh' might help.
| $
```

It is only after I select Abort that zypper gives me a clue of what is happening:  the repo cache needs to be refreshed.

Please improve the error message.

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
