### ISSUE TITLE
Machine-readable output formatting

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#126]
https://bugzilla.opensuse.org/show_bug.cgi?id=409370 asked for a way to make the output of "zypper locks" easily parseable by bash scripts.

One way to do this would be to provide a `--format` option which could take values like "json", "json-pretty", etc.

**Comment by elfring** [comment]
I am curious on how the software evolution will be continued for [the feature request (or bug report) “Adjustment of list results for easier postprocessing”](https://bugzilla.opensuse.org/show_bug.cgi?id=409370 "Checking possibilities for data postprocessing").

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.

**Comment by p-se** [comment]
I was just looking for such an option for automation. Maybe that's off-topic for production environments, but for development it would be a breeze to be able to do `zypper info <package> --format=json`. Is anything like this possible already?

**Comment by mlandres** [comment]
@p-se Sorry, no. 
We'd actually love to have a dedicated `query` command, where you can define data and format  you want to see as output. Something similar to rpms `--queryformat` option. ATM zypper search/info is pretty bad when it comes to producing machine readable output.
