### ISSUE TITLE
Add new flags to zypper to better support HTTPS access

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#127]
Echoing https://bugzilla.opensuse.org/show_bug.cgi?id=402329 and https://features.opensuse.org/323898  . . .

zypper(8) supports `https://` URLs but does not expose much of the parameterization 
of SSL queries that is supported by libcurl. 

As a simple example, you might have a repository that you only want made available 
via SSL (e.g., in order to protect unencrypted passwords in HTTP Basic authentication). 
Then there's no way to do the following: 

* Use a server SSL certificate not signed by a "real" (read: expensive) 
  certificate authority 
* Require a client SSL certificate 

It would be nice if zypper could be configured (either via command line flags or 
settings in /etc/zypp/repos.d/*) for the curl settings represented by these flags 
to curl(1): 

```
--insecure 
--cacert 
--cert 
--capath 
--engine 
--ciphers 
--egd-file 
--key 
--key-type 
--pass 
```

Perhaps the simplest thing to do is have some generic way of configuring libcurl. 
For example, any command line flag --curl-FOO (or setting curl-FOO=... in 
/etc/zypp/repos.d/*) would be equivalent to curl(1)'s --FOO flag.

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
