### ISSUE TITLE
zypper install needs Command Option to subtract packages from pattern

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#128]
Marc Benstein says in https://bugzilla.opensuse.org/show_bug.cgi?id=445893

zypper install needs Command Option to subtract packages from pattern

Such as zypper install -t pattern devel_C_C++ "but don't install cairo-devel"

Thanks, it'd be really nice not to use rm after install -t pattern

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
