### ISSUE TITLE
distribution-synchronization command for zypper, or way to delete packages that don't belong to any repository

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#130]
Elmar Stellnberger writes in https://bugzilla.opensuse.org/show_bug.cgi?id=739797

 A distribution-synchronization command for zypper would in my mind be a good idea: Sometimes it is better to strictly synchronize with all currently available package sources than to leave packages which have become unreachable in place. This means that packages which are no more available through any active repository will be deleted. This option can either be used for up- or downgrading and will always produce a clean system. Red Hats yum does already provide this feature. It could furthermore save us from implementing an even more complicated rollback system which would be more resource intense and sometimes also undesireable (installed some new packages in the meanwhile which we wanna keep.).

ncutler comment: maybe it would be enough to enable deletion of all packages that don't belong to any repository?

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github issue. Especially as our package submission policy asks for bugzilla references in the changes file, we preferably track in bugzilla. This kind of 'bugsquashing' is IMO nonsense. Reverting.

**Comment by smithfarm** [comment]
> This kind of 'bugsquashing' is IMO nonsense.

Anything to call attention to issues that are left open for half a decade or more. . .
