### ISSUE TITLE
zypper could display support info if available, not only when product == SUSE_SLE

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/zypper#131]
Michael Andres writes in https://bugzilla.opensuse.org/show_bug.cgi?id=764147

zypper info displays support info (L1,L2,L3,ACC) only if the base product is SUSE_SLE. Actually the info could be displayed if available (not unknown), independently from the kind of base product installed. 

(Also the test for 'base product is SUSE_SLE' is debatable. There are probably more enterprise products then 'SUSE_SLE', and this test does also affect the 'package not supported by it's vendor' and 'ACC' notifications)

**Comment by mlandres** [comment]
JFYI: It makes no sense to convert a zypp bugzilla entry into a zypp github
issue. Especially as our package submission policy asks for bugzilla references
in the changes file, we preferably track in bugzilla. Reverting.
