### ISSUE TITLE
(1/6) Installing: %s [.......done]

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/zypper#134]
Seen by openQA: https://openqa.opensuse.org/tests/484731#step/aplay/9

since the upgrade of zypper from 1.13.32 to 1.32.34, installation of packages no longer report their names installed.

**Comment by DimStar77** [comment]
snapshot 0912 cancelled due to this issue; zypper/libzypp upgrades will be reverted for 0913

**Comment by mlandres** [comment]
@DimStar77 Please try to use bsc bugreports (component libzypp) rather than github issues. You know the check-in policies require a bugnumber.

**Comment by DimStar77** [comment]
as you wish : https://bugzilla.opensuse.org/show_bug.cgi?id=1058695
(I'm not sure if a bnc ref would be needed here, as this is clearly an 'upstream' issue and this broken zypper version was in no product yet, so a bnc ref is also not mandatory; but I'll remember to keep zypp issues in bnc)

**Comment by mlandres** [comment]
Thanks.

**Comment by coolo** [comment]
as you reverted libsolv and libzypp, can someone please resubmit them - or just revert the revert?
