### ISSUE TITLE
Performan installs in intervals that are within disk space limits

### ISSUE THREAD

**Issue by janat08** [openSUSE/zypper#136]
The default 40GB system partition are idiotic without the settings even container snapper images. Would it be possible account for download/install needs and perform them in sets that are within limits of diskspace, rather than downloading everything at once, and then proceeding to install on top of that.

**Comment by mlandres** [comment]
You can use zypper option `--download-as-needed` or set the global default `commit.downloadMode = DownloadAsNeeded` in `/etc/zypp/zypp.conf`. This does alternating download and install. It's however less robust against network problems as an update might be interrupted in the middle if some package can't be downloaded.

**Comment by janat08** [comment]
--download-in-heaps is an option btw.

**Comment by mlandres** [comment]
JFYI: 'download-in-heaps' would be an option, if the resolver would fully support it. Up to now it's usually the same as `download-in-advance`.

**Comment by janat08** [comment]
I suppose this is about patterns, maybe it could be the default otherwise. Should I reopen?
