### ISSUE TITLE
[Request] Add ability to search and install the packages in the OBS repos

### ISSUE THREAD

**Issue by trmdi** [openSUSE/zypper#137]
Like the title says, I think `zypper` currently lacks of ability to directly search and install the packages in the OBS repos. Something like Arch's yaourt.

**Comment by mlandres** [comment]
In fact nothing we will code in zypper. On SLES they provide a zypper-search-packages-plugin which is able to search for packages in remote locations. openSUSE could provide such a plugin searching in OBS, etc. Depends on what's OBS offering to search.

@lnussel didn't you ask for a way to search remote locations? An openSUSE version of zypper-search-packages-plugin could be better than sipping the SLE package as we AFAIK do now.

**Comment by lnussel** [comment]
we have software.opensuse.org. A remote search would be possible to implement via that one. It is undesirable to search random obs repos though. that just calls for breaking systems. Since openSUSE has one big official repo that is enabled anyways, the use of this feature would be limited anyways.

**Comment by trmdi** [comment]
Ok. I think so now. You could close the issue if you want. Thank you.
