### ISSUE TITLE
zypper lr terminates when lang is other then English

### ISSUE THREAD

**Issue by Fisiu** [openSUSE/zypper#145]
Issuing command `zypper lr` fails with:
```zsh
fisiu@pendrak:~ $ zypper lr       
Priorytety repozytoriów mające zastosowanie:                                                                                                                          (Zobacz 'zypper lr -P', aby uzyskać szczegóły)
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::too_many_args> >'
  what():  boost::too_many_args: format-string referred to fewer arguments than were passed
[1]    32716 abort (core dumped)  zypper lr
```

However when `LANG=C` is specified, then it works as expected:
```zsh
fisiu@pendrak:~ $ LANG=C zypper lr
Repository priorities in effect:                                                                                                                                                    (See 'zypper lr -P' for details)
      90 (raised priority)  :  1 repository  
      95 (raised priority)  :  3 repositories
      98 (raised priority)  :  1 repository  
      99 (default priority) :  7 repositories
     120 (lowered priority) :  1 repository  

#  | Alias               | Name                               | Enabled | GPG Check | Refresh
---+---------------------+------------------------------------+---------+-----------+--------

          REPOSITORIRES HERE

```

My current settings are:
```zsh
fisiu@pendrak:~ $ localectl status
   System Locale: LANG=pl_PL.UTF-8
       VC Keymap: pl
      X11 Layout: pl
       X11 Model: microsoftpro
     X11 Options: terminate:ctrl_alt_bksp
```

If you need anything else, please let me know.

**Comment by mlandres** [comment]
```
zypp-head:~ (0) $ LANG=pl_PL.UTF-8 zypper lr
Priorytety repozytoriów nie mają zastosowania. Wszystkie włączone repozytoria współdzielą ten sam priorytet.

# | Alias      | Nazwa      | Włączono | Sprawdzaj GPG | Odśwież
--+------------+------------+----------+---------------+--------
```
it works for me as expected, however my message is slightly different than yours. I tried zypper 1.14.1 (Tumbleweed) and 1.13.28 (Leap 42.3). @Fisiu which version are you using?

**Comment by Fisiu** [comment]
```zsh
fisiu@pendrak:~ $ zypper --version
zypper 1.14.1
```

It seems it's related to repositories priorities I have set. They are different across all repositories.
There are some with priority 90 and 120. There are some with default priority 99 as well.

**Comment by mlandres** [comment]
```
$ LANG=pl_PL.UTF-8  zypper lr
Priorytety repozytoriów mające zastosowanie:             (Zobacz 'zypper lr -P', aby uzyskać szczegóły)
      90 (podniesiony priorytet) :  1 repozytorium    
      99 (domyślny priorytet)    :  2 repozytoria(-ów)
     120 (obniżony priorytet)    :  1 repozytorium    

# | Alias      | Nazwa      | Włączono | Sprawdzaj GPG | Odśwież
--+------------+------------+----------+---------------+--------
```
The error message indicates a problem in the translated string (a missing %-placeholder), but I can not reproduce it; neither with 1.14.1 nor with a newer or older version. 

- Please run `rpm -V zypper`. If the output mentions `/usr/share/locale/pl/LC_MESSAGES/zypper.mo` reinstall zypper: `zypper in -f zypper`
- Use `find /usr/local/share/locale`  to be sure there are *no*  `zypper.mo` files installed below `/usr/local`
- If it still does not work run `ZYPP_LOGFILE=/tmp/zypper-issue-145.log zypper lr` and send me the the log file `/tmp/zypper-issue-145.log` (pastebin, email, .. as you like).
If you have `strace` installed please add the output of `strace zypper lr 2>&1 | grep 'open.*/pl' | grep -v ENOENT`

**Comment by Fisiu** [comment]
I found an issue in translation of https://github.com/openSUSE/zypper/blob/master/src/repos.cc#L204
You were right about placeholder issue. I already fixed translation in git master branch via l10n portal.

**Comment by mlandres** [comment]
Thanks!
