### ISSUE TITLE
Orphaned Packages

### ISSUE THREAD

**Issue by jatin-zlatanist** [openSUSE/zypper#147]
BUG: Fixed on Tumbleweed but not on Leap (42.3) On running "sudo zypper packages --orphaned" it shows the openSUSE-dvd-release which might be problematic for new users and if they remove it it breaks their whole system. Please FIX :)
![screenshot from 2018-02-07 19-40-39](https://user-images.githubusercontent.com/29427382/35920782-d80ef684-0c3e-11e8-8a84-c2371010046e.png)

**Comment by mlandres** [comment]
This is nothing that can be fixed or influenced by zypper. A package is *orphaned*, if it is not available in one of the enabled repositories. 
The Leap-42.3 online repo should probably provide this package. I filed https://bugzilla.suse.com/show_bug.cgi?id=1081209 for you.

**Comment by jatin-zlatanist** [comment]
It goes away if we enable the dvd or usb repository which comes along a dvd or usb installer but then ofcourse its not an online repo so it gives error repo not found !
