### ISSUE TITLE
What causes "packages have no support information from their vendor" message by zypper?

### ISSUE THREAD

**Issue by rakeshsinghranchi** [openSUSE/zypper#153]
**Repro steps:**
~$ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
~$ sudo sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl= https://packages.microsoft.com

When installing the SDK, SUSE and OpenSUSE may report that nothing provides libcurl. libcurl should already be installed on supported versions of both distros. Run zypper search libcurl to confirm. The error will present 2 'solutions'. Choose 'Solution 2' to continue installing .NET.

~$ sudo zypper update
~$ sudo zypper install libunwind libicu
~$ sudo zypper install dotnet-sdk-2.1.4

RPM spec file has "Vendor" field in it.

Name        : dotnet-host
**Vendor      : .NET Foundation**

**OS details:**
cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

**Comment by mlandres** [comment]
The package is named `libcurl4`:

    $ zypper search libcurl 
    
    S  | Name                | Summary                                | Type   
    ---+---------------------+----------------------------------------+--------
    i  | libcurl4            | Version 4 of cURL shared library       | package

To answer your question:

On SLES packages without or with unknown support status (L1, L2, L3,Additional Customer Contract Necessary,..) are reported.

Information about the support status is not encoded in a rpm header, so it is not part of standard repo metadata. The information may be shipped in a SUSE specific extension file named `susedata.xml`. If it's not available the package will be reported to keep the admin informed.
