### ISSUE TITLE
[feature request]Install packages in parallel (threaded)

### ISSUE THREAD

**Issue by romulasry** [openSUSE/zypper#154]
This would speed the install times quite a bit. Any recent work on this?

**Comment by mlandres** [comment]
No. Predictable install order must be guaranteed. And rpm does not grant parallel access to the database anyway. Packages wont be installed in parallel.

**Comment by romulasry** [comment]
rpm-4.2 and later has concurrent access, so parallel installs are permitted.
Source: https://www.redhat.com/archives/rpm-list/2003-September/msg00058.html

You also could also use libsolv to install prerequisite packages first, if so desired, no?

**Comment by mlandres** [comment]
Libsolv already orders packages accordingly. We need this anyway, because libzypp does not install packages by using librpm. As long as rpm itself does not support it, packages wont be installed in parallel.

**Comment by romulasry** [comment]
rpm supports it, if they are non-conflicting, according to: https://github.com/rpm-software-management/rpm/issues/404#issuecomment-369860852

**Comment by mlschroe** [comment]
No, that's not true. Don't believe everything you read ;)
Rpm will not install packages in parallel due to the transaction lock.

**Comment by SRCxiaojin** [comment]
> rpm-4.2 and later has concurrent access, so parallel installs are permitted.
> Source: https://www.redhat.com/archives/rpm-list/2003-September/msg00058.html
> 
> You also could also use libsolv to install prerequisite packages first, if you re-coded it to do so, no?

how to use libsolv to install prerequisite packages first?could you share me some guide

**Comment by mlandres** [comment]
Libsolv uses a `Transaction` object to compute the install order. Check the example [solv.c](https://github.com/openSUSE/libsolv/blob/master/examples/solv/solv.c) to see how it can be used.

**Comment by SRCxiaojin** [comment]
> Libsolv uses a `Transaction` object to compute the install order. Check the example [solv.c](https://github.com/openSUSE/libsolv/blob/master/examples/solv/solv.c) to see how it can be used.

I check the code , finnally call runrpm function to install,from the function, we can see
execlp("rpm", "rpm", arg, "--force", "--nodeps", "--nodigest", "--nosignature", "--root", rootdir, name, (char *)0);
it fock a new process ,and wait it done.
I think it is not parallel, but serial in fact.plz help check again

**Comment by mlandres** [comment]
Of course it's serial, see mlschroe s comment.
