### ISSUE TITLE
feature request: --installroot option

### ISSUE THREAD

**Issue by vrothberg** [openSUSE/zypper#157]
dnf ships an `--installroot` option, which the [man page](https://dnf.readthedocs.io/en/latest/command_ref.html) describes as follows:

> Specifies an alternative installroot, relative to where all packages will be installed. Think of this like doing chroot <root> dnf except using --installroot allows dnf to work before the chroot is created.

Zypper's `--root` option comes close to that, but it does slightly more than necessary as `--installroot` will still use the hosts repositories, caches, metadata, etc. I have a specific use-case for such a feature in zypper, as I'd love to mount a container's rootfs (with no zypper installed to reduce size) and use the host's zypper to, for instance, install a new package in the container's rootfs.

**Comment by mlandres** [comment]
@bzeller would you like to look into this?
