### ISSUE TITLE
Automatic retry with max retries and timeout in non-interactive mode

### ISSUE THREAD

**Issue by okurz** [openSUSE/zypper#177]
## Motivation

openQA test in scenario sle-12-SP3-Server-DVD-Incidents-x86_64-mau-extratests@64bit fails in
[zypper_ref](https://openqa.suse.de/tests/1721833/modules/zypper_ref/steps/4)
with a 502 "Bad Gateway" error. We run zypper in our openQA tests with the "--non-interactive" option which seems to not regard any retry and therefore fails immediately on occassional network problems.

## Expected result

Would be great if the non-interactive mode would also offer automatic retries. Optionally on top: Command line options for e.g. --max-retries and --retry-wait-time (for waiting between the retries)

## Further details

Always latest result in this scenario: [latest](https://openqa.suse.de/tests/latest?distri=sle&arch=x86_64&flavor=Server-DVD-Incidents&version=12-SP3&machine=64bit&test=mau-extratests)

**Comment by mlandres** [comment]
Related to [Bug 1070851 - 502 Bad Gateway in update OS](https://bugzilla.suse.com/show_bug.cgi?id=1070851)
