### ISSUE TITLE
German translation error

### ISSUE THREAD

**Issue by imphil** [openSUSE/zypper#178]
I don't know exactly where to report this, but hopefully you can redirect this to the right channel.

The translation of src/callbacks/keyring.h:51 to German (https://github.com/openSUSE/zypper/blob/master/po/de.po#L226) has an error.

WRONG: "vertrauenswürdig ist. Sie sollten nur fortfahren, wenn Sie wissen, das die "
RIGHT: "vertrauenswürdig ist. Sie sollten nur fortfahren, wenn Sie wissen, dass die "

**Comment by mlandres** [comment]
Thanks.
