### ISSUE TITLE
zypper search and info don't know about the reverse depedency.

### ISSUE THREAD

**Issue by trmdi** [openSUSE/zypper#184]
Look at these commands:

    ▶ sudo zypper in --recommends mpv
    ...
    The following 4 NEW packages are going to be installed:
    mpv mpv-bash-completion mpv-plugin-mpris mpv-zsh-completion

    ▶ sudo zypper se --recommends mpv-plugin-mpris
    No matching items found.

    ▶ sudo zypper if --recommends mpv
    Information for package mpv:
    ----------------------------
    Repository     : openSUSE-Tumbleweed-Oss 
    ...
    Recommends     : youtube-dl 

I think `zypper se --recommends mpv-plugin-mpris` and `zypper if --recommends mpv` should know about this reverse-Recommends.

**Comment by mlandres** [comment]
There's indeed no `--supplements` () available for `search` and `info`. yes, we should add this.
