### ISSUE TITLE
Zypper should not rewrite repo files when it reads them

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/zypper#194]
Zypper's behavior of rewriting repo files when it reads them is difficult to cope with.

This is especially a problem in the Red Hat/Fedora ecosystem because repo files are shipped in RPM packages (In CentOS, it's in `centos-release`, Fedora ships them in `fedora-repos`, RPMFusion ships in `rpmfusion-release`, etc.). The repo files are marked as `%config(noreplace)` (per policy), but Zypper changes the files in a completely unexpected manner (no edits requested by the user), which means that package upgrades do not update the repo configuration at all.

This is also a problem for third-parties who ship their repo configs this way (for example, [Datto's repo for dattobd is done this way for openSUSE](https://github.com/datto/dattobd/blob/master/INSTALL.md#opensuse)). I get that Zypper applies defaults and whatnot, but it shouldn't be writing those back into the file if there's no reason to.

**Comment by mlandres** [comment]
Should be fixed by  openSUSE/libzypp@659851f80977d4f4a0effda699ea9ad5b1f8f3aa. Remembering the probed type in the .repo file is actually not needed.
