### ISSUE TITLE
Usability on transactional server

### ISSUE THREAD

**Issue by brejoc** [openSUSE/zypper#199]
[[Feature request] Implement transactional-update into zypper](https://github.com/openSUSE/zypper/issues/198) made me think about the usability of zypper on a transactional server. Using zypper on a transactional server directly is pointless, because the root-fs is read-only. That is perfectly clear. But zypper still lets you happily type `zypper dup` and then starts to fetch 300 new packages. Once the installation starts and you'll get something like this:

```
Checking for file conflicts: ..................................................................................[done]
(  1/374) Removing libx86emu1-1.14-1.2.x86_64 ................................................................[error]
Removal of (54167)libx86emu1-1.14-1.2.x86_64(@System) failed:
Error: Subprocess failed. Error: RPM failed: error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Read-only file system)
```

There are three scenarios why this might have happen:

1. The admin is not aware of how to interact with a transactional server and is lost now.
2. The admin forgot that this is not a traditional server and tried to upgrade it in the usual way.
3. This shows up in the logs or error messages of SaltStack, because the admin used `pkg.update` to update the system.

The first case is bad, because now the admin has to search the internetz to find a solution. The second case is also bad, because the seasoned admin has wasted precious time (and bandwidth) only to see that she/he should have used `transactional-update`. The third case might also stem from case one or two, but is only much better hidden in an error message.

I see two possibilities here:

1. Let zypper fail immediately and show a message to the user.
2. Don't expose zypper on a transactional server.

Okay, maybe I should have filed the issue somewhere else, but let's just start the discussion here. :wink: 

/cc @sysrich

**Comment by sysrich** [comment]
Note, not all zypper commands fail on a transactional server

For example, `zypper ar`, `rr` and such always work, `zypper ref` often works unless refreshing an untrusted new repo

**Comment by mlandres** [comment]
Yes, I already created a trello card when closing #198. We will at least extend the check for being root when running install commands to include a check whether we have a rw-mounted root. Then we'll see whether further hints are necessary.

**Comment by brejoc** [comment]
Very cool! Thanks @bzeller!
