### ISSUE TITLE
Cannot scroll license screen using arrow keys or PgUp/Down

### ISSUE THREAD

**Issue by Qantas94Heavy** [openSUSE/zypper#218]
When updating a non-free package, the license screen displays the following:

    (Use arrows or pgUp/pgDown keys to scroll the text by lines or pages.)

However, none of these keys have any effect -- the relevant commands for `more` should be used instead.

**Comment by mlandres** [comment]
Zyppers default pager is `more` and may be overwritten by the `$PAGER` environment variable. If you see `Use arrows or pgUp/pgDown` then your `$PAGER` environment variable probably says `*less`.

I'd need to know what actually got called. `echo $PAGER` might help as well as `grep 'start_program.*Executing' /var/log/zypper.log`, which lists all programs zypper called. The paher should be among them.

**Comment by bzeller** [comment]
Closed because required information was not provided
