### ISSUE TITLE
[feature request] Short command name: zp, zi and zr

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/zypper#263]
Zypper might be the most used command for openSUSE users. However, the command name is longer compared to common commands: ls, cd, rm, vi, cp, etc.

So I suggest the following short commands for zypper.

```
zp -- zypper
zi -- zypper install
zr -- zypper remove
zu -- zypper up/dup
```

I have searched these with `cnf` and they are not used by any packages in openSUSE official repository.

**Comment by mlandres** [comment]
Sorry, but we won't add such shortcuts to zypper itself. 
But you can easily add alias definitions like `alias zp=zypper` or `alias zi='zypper install'` to your `~/.bashrc` if you find them handy. (accordingly for other shells).
