### ISSUE TITLE
Permission denied when running zypper up or zypper ref with http://download.opensuse.org/......

### ISSUE THREAD

**Issue by mixedup4x4** [openSUSE/zypper#276]
Permission to access 'http://download.opensuse.org/update/leap/15.0/oss/repodata/935e645fa9073c17b7984d3e536af1b0e1206f79a15340cfc0fa79447cf9f5e3-primary.xml.gz' denied

**Comment by mlandres** [comment]
The file no longer exists on the server. 
Are you using old repo metadata? If autorefresh is turned off for your repo,  turn it on or manually call `zypper ref`. By the info you provided, it does not seem to be a zypper issue.

**Comment by mixedup4x4** [comment]
I was able to get i sorted out.  After switching my repos to mirrors, I was good.  The I noticed the updates really didn't exist on that mirror.  After some playing around, I got the actual opensuse repos to work.  I deleted them all, zypper clean all -s, and a reboot before finally adding the repos back with success
