### ISSUE TITLE
ctest cannot find tests with CMake 3.14

### ISSUE THREAD

**Issue by gruenich** [openSUSE/zypper#279]
With CMake 3.14 ctest cannot find the tests to execute. Thus building the package fails which prevents openSuse from integrating CMake 3.14 into Factory.
Currently the error occurs here: https://build.opensuse.org/project/show/openSUSE:Factory:Staging:M

**Comment by gruenich** [comment]
Fixed in zypp:Head/zypper by adding -DENABLE_BUILD_TESTS=ON \ to the spec file. Please push this to Factory and my problem is gone.

**Comment by bzeller** [comment]
Michael is back on Tuesday, he can push a new version.

**Comment by mlandres** [comment]
Pushed `zypper-1.14.28` to factory (osc req. #709138)
