### ISSUE TITLE
--repo option cause dependency missing

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/zypper#280]
Reproduce in Tumbleweed:

```
sudo zypper addrepo https://download.opensuse.org/repositories/Emulators/openSUSE_Tumbleweed/Emulators.repo
sudo zypper refresh
sudo zypper install --repo Emulators m64py
```

Then I got `python-PySDL2` dependency missing issue. But this package should be in official repository.

It works without `--repo` option:

```
sudo zypper install m64py
```

The two ways install the same package.

**Comment by bzeller** [comment]
Please create and attach a solver testcase:
```
# zypper in --debug-solver zypper install m64py
...
Generating solver test case...
Solver test case generated successfully at /var/log/zypper.solverTestCase.
```

Then pack the output directory together with /var/log/zypper.log and attach it
to the bugreport.

https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

In case the testcase exceeds the 25MB limit for github uploads, you can use
'split' to divide the file into smaller pieces:

```
$ cd /tmp
$ tar cvjf zypper.solverTestCase.tar.bz2 /var/log/zypper.solverTestCase/
$ split -b 25M --additional-suffix=-zypper.solverTestCase.tar.bz2 \
zypper.solverTestCase.tar.bz2
```
The created pieces will be named like this:
```
xaa-zypper.solverTestCase.tar.bz2
xab-zypper.solverTestCase.tar.bz2
xac-zypper.solverTestCase.tar.bz2
> ...
```

**Comment by guoyunhe** [comment]
I run:
```
sudo zypper install --debug-solver --repo Emulators m64py
```
Here is the result:
[zypper.solverTestCase.tar.gz](https://github.com/openSUSE/zypper/files/3246595/zypper.solverTestCase.tar.gz)

**Comment by bzeller** [comment]
This is not a bug, if you use --repo this means that you use ONLY the repositories given on the commandline. python-PySDL2 is in the main repositories, but those are excluded by your command. What are you trying to archive using the --repo option?

**Comment by guoyunhe** [comment]
I have multiple repository that provide m64py package. So I want to make sure I installed it from Emulators repository.

**Comment by bzeller** [comment]
In case you want to enforce using the repository try:
`sudo zypper install  --from Emulators m64py`

**Comment by guoyunhe** [comment]
Oh, thanks!
