### ISSUE TITLE
how to create _constraints file to be placed in OBS ?

### ISSUE THREAD

**Issue by michelmno** [openSUSE/zypper#286]
to avoid "Out of memory: Killed process ... (lto1-ltrans)..."
I need to add a _constraints file similar to https://build.opensuse.org/package/view_file/home:michel_mno:branches:zypp:Head/zypper/_constraints?expand=1

I do not understand where to place it in this git tree, and what to be modified for the new file to be copied to OBS.

**Comment by mlandres** [comment]
Just the tarball, .spec and.changes are created from git and uploaded to OBS by our CI machines.

All other files in the project, like zypper-rpmlintrc or your _constraints, are OBS specific static content and need to be manually uploaded to the project that needs them.

**Comment by michelmno** [comment]
I am unable to submit a request to add _constraints file in zypp:Head project as following error:
```
Server returned an error: HTTP Error 403: Forbidden
The target project zypp:Head is not accepting requests because: Please create a pull request in https://github.com/openSUSE/...
```

**Comment by mlandres** [comment]
I see, a submit request regarding OBS metadata is not common. I add the file for you.

**Comment by michelmno** [comment]
> I see, a submit request regarding OBS metadata is not common. I add the file for you.

Thank you for the manual copy of _constraints.
