### ISSUE TITLE
Packages mixed from different repos if version is exactly the same

### ISSUE THREAD

**Issue by toabctl** [openSUSE/zypper#288]
I have a source package (called openstack-neutron) that produces some binary packages. I have theses packages in 2 different repos (one called `cloud`, the other `upstreamcloud`).

```
# zypper se -s openstack-neutron
...
S  | Name                                    | Type       | Version           | Arch   | Repository   
---+-----------------------------------------+------------+-------------------+--------+--------------
i  | openstack-neutron                       | package    | 14.1.0~dev685-1.1 | noarch | upstreamcloud
v  | openstack-neutron                       | package    | 14.1.0~dev685-1.1 | noarch | cloud        
v  | openstack-neutron-linuxbridge-agent     | package    | 14.1.0~dev685-1.1 | noarch | upstreamcloud
i  | openstack-neutron-linuxbridge-agent     | package    | 14.1.0~dev685-1.1 | noarch | cloud        
i  | openstack-neutron-server                | package    | 14.1.0~dev685-1.1 | noarch | upstreamcloud
v  | openstack-neutron-server                | package    | 14.1.0~dev685-1.1 | noarch | cloud
```

The problem here is, that `openstack-neutron` is installed from `upstreamcloud` but `openstack-neutron-linuxbridge-agent` is installed from `cloud`. I think if the versions are identical, zypper should install only from a single repository.

**Comment by bzeller** [comment]
I guess all the repositories you registered have the same priority `zypper lr -p`. That means for zypper all the repositories are equal. There is no "use dependencies from the same repository first". However you can raise the prio from one of those repos. Or you can run a 'zypper dup  --allow-vendor-change --from <oneoftherepos>' to get the packages from a specific one. 

However this is not a issue, closing.
