### ISSUE TITLE
Why and How to change "The following xx package updates will NOT be installed:"

### ISSUE THREAD

**Issue by Twoflower2** [openSUSE/zypper#290]
1. Why do I get 

> The following 130 package updates will NOT be installed:

2. How do I change things to install those 130 updates? (I do not want to install FF because Leap 15.1 FF is super old)

[zypper_output.txt](https://github.com/openSUSE/zypper/files/3604064/zypper_output.txt)

**Comment by bzeller** [comment]
Maybe the zypper log can show why its not installing the packages:
`sudo zypper log` will give you the last zypper runs, `sudo zypper log <pid>` will give you the log
of a specific zypper run. Please attach the log file so we can see what is happening.

**Comment by Twoflower2** [comment]
Most probably something I have set somehow, but will be good to know what and how to resolve.

[zypper_log.txt](https://github.com/openSUSE/zypper/files/3604248/zypper_log.txt)
