### ISSUE TITLE
zypper SEGFAULT on access to only-one repo: leap/15.1/repo/oss ?

### ISSUE THREAD

**Issue by pgnd** [openSUSE/zypper#305]
I've got a numner of machines, all running Leap 15.1

2 days ago, no problems with `zypper up` or `zypper dup`

Today, a bunch are segfaulting @ one specific distribution repo
```
zypper -vv up
	...
	Checking whether to refresh metadata for OS15-non-oss
	Retrieving: repomd.xml ................................................................................................[done]
	Retrieving: media .....................................................................................................[done]
	Checking whether to refresh metadata for OS15-oss
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/media.1/media ................................................................................................................................................................[done]
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/repomd.xml.asc ......................................................................................................................................................[done]
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/repomd.xml.key ............................................................................................................................................[done (988 B/s)]
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/repomd.xml ..........................................................................................................................................................[done]
	  Repository:       OS15-oss
	  Key Name:         openSUSE Project Signing Key <opensuse@opensuse.org>
	  Key Fingerprint:  22C07BA5 34178CD0 2EFE22AA B88B2FD4 3DBDC284
	  Key Created:      Mon 05 May 2014 01:37:40 AM PDT
	  Key Expires:      Thu 02 May 2024 01:37:40 AM PDT
	  Rpm Name:         gpg-pubkey-3dbdc284-53674dd4
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/12756b0bcbe274b3bdf178191baea85635c717e3321644fb2ca8807e36be87fa-primary.xml.gz .....................................................................................[done]
	Retrieving: http://download.opensuse.org/distribution/leap/15.1/repo/oss/repodata/57cb86253c19b7c80ce4de1fb5a081a842e24eac5308c84b159d6728e3edc183-appdata.xml.gz ---------------------------------------------------------------------------------[starting]Segmentation fault (core dumped)
	...
```

journal reports,

```
journalctl
	...
	Nov 11 13:37:51 prod223 kernel: [13139.140228] zypper[26689]: segfault at 6d6172617088 ip 00007fbced4c5961 sp 00007ffdf070a3e0 error 4 in libcurl.so.4.6.0[7fbced488000+88000]
	Nov 11 13:37:51 prod223 kernel: [13139.140236] Code: 8c 94 00 00 00 39 71 28 0f 8c 8b 00 00 00 0f 1f 00 49 89 41 08 49 89 c1 48 8b 40 08 48 39 78 20 7e bd 48 8b 10 48 85 d2 74 3f <48> 39 7a 20 7f 19 7c 05 39 72 28 7f 12 48 89 c2 49 89 10 49 89 d0
	Nov 11 13:37:51 prod223 kernel: [13139.140245] RIP: 0033:0x7fbced4c5961
	Nov 11 13:37:51 prod223 kernel: [13139.140246] Code: 8c 94 00 00 00 39 71 28 0f 8c 8b 00 00 00 0f 1f 00 49 89 41 08 49 89 c1 48 8b 40 08 48 39 78 20 7e bd 48 8b 10 48 85 d2 74 3f <48> 39 7a 20 7f 19 7c 05 39 72 28 7f 12 48 89 c2 49 89 10 49 89 d0
	Nov 11 13:37:51 prod223 kernel: [13139.140247] RSP: 002b:00007ffdf070a3e0 EFLAGS: 00010202
	Nov 11 13:37:51 prod223 kernel: [13139.140248] RAX: 000055e3802b0da8 RBX: 000055e380270938 RCX: 000055e380270938
	Nov 11 13:37:51 prod223 kernel: [13139.140249] RDX: 00006d6172617068 RSI: 0000000000053d91 RDI: 0000000000003353
	Nov 11 13:37:51 prod223 kernel: [13139.140250] RBP: 0000000000003353 R08: 00007ffdf070a3e0 R09: 00007ffdf070a3e0
	Nov 11 13:37:51 prod223 kernel: [13139.140251] R10: 00007ffdf070a420 R11: 0000000000003353 R12: 0000000000053d91
	Nov 11 13:37:51 prod223 kernel: [13139.140251] R13: 000055e380270938 R14: 000055e380218890 R15: 000055e380270ae0
	Nov 11 13:37:51 prod223 kernel: [13139.140252] FS:  00007fbcef7caa00 GS:  0000000000000000
	...
```

If I *disable* that ONE repo, http://download.opensuse.org/distribution/leap/15.1/repo/oss, all's good -- a;; OTHER repos are ok/updated, and zypper execs.

Of course, that repo IS disabled ...

I've never seen a repo-specific segfualt b4.

any clues/hints?  more info needed?

**Comment by pgnd** [comment]
noting @

https://build.opensuse.org/package/show/devel:libraries:c_c++/curl

"buildservice-autocommit accepted request 746072 about 10 hours ago (revision 263) "

disabling repo OS15-oss

then force installing
```

zypper in --force \
 curl-7.60.0-lp151.5.6.1.x86_64 \
 libcurl4-7.60.0-lp151.5.6.1.x86_64

	...
	The following 2 packages are going to be downgraded:
	  curl libcurl4

	The following 2 packages are going to change vendor:
	  curl      obs://build.opensuse.org/devel:libraries:c_c++ -> openSUSE
	  libcurl4  obs://build.opensuse.org/devel:libraries:c_c++ -> openSUSE
	...

```

then RE-enable repo OS15-oss

now, no more SEGFAULT.  zypper functions normally

**Comment by pgnd** [comment]
x-ref,

https://bugzilla.opensuse.org/show_bug.cgi?id=1156481

**Comment by mimi1vx** [comment]
@pgnd are you using development repository on Leap? Even more repository with base libraries? so why you surprised with problems?

**Comment by mlandres** [comment]
@pgnd The most interesting question is which zypper/libzypp version are you using?

[bsc#1146027](https://bugzilla.suse.com/show_bug.cgi?id=1146027) describes random crashes in libcurl with `libzypp < 17.14.1`. It's a libcurl issue, nevertheless  we removed the `CURL_HTTP_VERSION_2TLS` flag in libzypp-17.14.1 as it seems to trigger the crashes.

Apart from that I'm curently using `curl-7.67.0-lp151.272.1` from `devel:libraries:c_c++` without any problem.

**Comment by pgnd** [comment]
@mimi1vx Bad assumption on your part; I'm never surprised with problems.  I *am* fed up with that lame question ... Would you prefer that we siimply stop communicating when they exist?   

@mlandres
Looks like libzypp-17.15.0-lp151.2.3.2.x86_64 here ...
I'll keep poking at libcurl, thx!

**Comment by pgnd** [comment]
@mlandres 
fyi re: zypp version

with
```
	rpm -qa | egrep "\-solv|curl|zypp" | sort
		curl-7.67.0-lp151.272.1.x86_64
		libcurl4-7.67.0-lp151.272.1.x86_64
		libcurl-devel-7.67.0-lp151.272.1.x86_64
		libzypp-17.15.0-lp151.2.3.2.x86_64
		python3-solv-0.7.6-lp151.2.3.2.x86_64
		python-solv-0.7.6-lp151.2.3.2.x86_64
		zypper-1.14.30-lp151.2.3.1.x86_64
```

exec of
```
	zypper ...
```

still SEGFAULTs at access to only

	http://download.opensuse.org/distribution/leap/15.1/repo/oss

repo.

bump to
```
	rpm -qa | egrep "\-solv|curl|zypp" | sort
		curl-7.67.0-lp151.272.1.x86_64
		libcurl4-7.67.0-lp151.272.1.x86_64
		libcurl-devel-7.67.0-lp151.272.1.x86_64
+		libzypp-17.16.0-lp151.5.5.x86_64
+		python3-solv-0.7.8-lp151.3.1.x86_64
+		python-solv-0.7.8-lp151.3.1.x86_64
+		zypper-1.14.32-lp151.17.1.x86_64
```

from

	https://download.opensuse.org/repositories/zypp:/SLE-15-SP1-Branch/openSUSE_Leap_15.1_Update/

also fixes the problem

**Comment by mlandres** [comment]
Good news, but strange. libzypp has almost no code changes between 17.15 and 17.16 and nothing regarding the media/curl backend. Almost looks like recompiling it actually solved the issue. We'll see if it stays fixed...

**Comment by pgnd** [comment]
@mlandres 

unfortunately, strangeness continues :-/ Sigh.

starting with a segfaulting setup, if I 

	(1) downgrade to curl/libcurl v7.60

or

	(2) upgrade to SLE repo, above

I can _immediately_ get past the zypper SEGFAULT @ OS15-oss repo.

But, once I *reboot*, systems with

	(1) continue to zypper exec with no issues

but those with

	(2) segfault again, still at the one repo

If I downgrade those (2) systems to (1), i.e., curl/libcurl 7.60 then they're IMMEDIATELY ok, without reboot. And, across reboot.

Strange is one good word for it.

This is 'real', but I need to tighten-up the test cases ...

**Comment by mlandres** [comment]
@pgnd  I'd bet it's a libcurl and/or openssl issue. IMO you should file a bugreport at bugzilla.opensuse.org against libcurl. Maybe the curl maintainers have some idea how to investigate/debug this. You can put me ma(at)suse.com into the CC.

For libzypp (zypper) you can just set `ZYPP_MEDIA_CURL_DEBUG=2` in the environment to log http headers and server responses. Not sure if it helps, but it won't do harm. After a crash please attach a `/var/log/zypper.log` to the bugreport. Maybe it reveals something. If you can, also `rpm -qa` and `uname -a` from a system that crashes. We can try to rebuild a system using the same package versions as yours. 

About the [`CURL_HTTP_VERSION_2TLS` ](https://curl.haxx.se/libcurl/c/CURLOPT_HTTP_VERSION.html) option we no longer set in libzypp since 17.14.1: The docs say it's the default in libcurl since `7.62.0`. This may explain why downgrading to 7.60 cures the system.

**Comment by mlandres** [comment]
@pgnd I'll reopen and reassign your [bsc#1156481](https://bugzilla.opensuse.org/show_bug.cgi?id=1156481). You can attach the files there.

**Comment by mlandres** [comment]
Closing it here. Issue continues at [bsc#1156481](https://bugzilla.opensuse.org/show_bug.cgi?id=1156481)

**Comment by mlandres** [comment]
**Result:** Bug in curl-7.67.0. Fix is on the way to Tumbleweed.
Thanks @pgnd for report and assistance.
