### ISSUE TITLE
[feature request] Display the Recommonds packages during install and update if disabled

### ISSUE THREAD

**Issue by cryptomilk** [openSUSE/zypper#310]
zypper provides and option `installRecommends = no` to disable the installation of packages which are recommened. If the install is disabled it would be nice to allow to display them. Then if I install a new package or update packages, I could see what is recommended and might install them hand selected later.

**Comment by mlandres** [comment]
If `installRecommends = no`, the resolver does not  consider recommends, so we can't easily show hat would have been installed if recommends would have been considered.
You can do `zypper info --recommends PACKAGE` to see what a specific package recommends.

**Comment by mlandres** [comment]
Duilicate of #206
