### ISSUE TITLE
Does zypper support Requires: style version expressions?

### ISSUE THREAD

**Issue by brianjmurrell** [openSUSE/zypper#329]
With [`yum`](https://github.com/rpm-software-management/yum) and it's successor [`dnf`](https://github.com/rpm-software-management/dnf) I can ask them to install versions in the same expression format that `Requires:` takes such as:

```bash
# dnf install 'foo >= 1.0rc1'
```

Can `zypper` do any such thing?

**Comment by mlschroe** [comment]
Of course!
