### ISSUE TITLE
Pattern Problem

### ISSUE THREAD

**Issue by 210hcl** [openSUSE/zypper#338]
I intalled my OpenSUSE Tumberweeded with some patterns such as patterns-base-x11, and I cancelled to choose some package such as lightm (I use sddm instead). But when I upgrade my system with "zypper dup", zypper tells me to install lightdm again. Is this a bug in zypper?

**Comment by mlandres** [comment]
No. Removing a package does not ban it from the system If you later install a different package, that requires (or recommends) it, it may get selected again. If you want to keep it off system persistently, you must lock it after removal:
> zypper rm lightdm
 zypper al lightdm
