### ISSUE TITLE
Is it possibile to use libaria2 instead of libcurl

### ISSUE THREAD

**Issue by 210hcl** [openSUSE/zypper#339]
Aria2 is a great download lib which can parallelly download. I am in China amd the server of the main openSUSE download server is not in a same continent which causeed zypper use to much time to request openSUSE server to find the nearest server. If zypper can use libaria2 to parrlled download, it will be more efficient,

**Comment by bzeller** [comment]
Hi, we are currently working on improving download speed, switching the backend library however would not help. LibCurl is also very well capable of downloading in parallel, however the rest of the code needs to be refactored to actually use those capabilities. 
So we will not switch to libaria2.

If you are using Leap you can try to switch off delta packages in the `/etc/zypp/zypp.conf` and see if that makes your downloads faster (this won't help on Tumbleweed):
`download.use_deltarpm = false`

You could also try to manually change the URLs in your repositories away from the official opensuse servers and use a mirror that is close to you directly.
