### ISSUE TITLE
Suggestion: zypper should block reboot

### ISSUE THREAD

**Issue by rkoot** [openSUSE/zypper#340]
Suggestion:
It would be nice if zypper somehow informed systemd about system updates, so systemd can block or schedule a user-performed reboot.
This ensures a reboot doesn't occur halfway an update and leave you with a potentially broken system.
I ran into this when performing a remote update on a user's system who decided to reboot his system halfway the update procedure. It resulted in a broken system.

**Comment by bzeller** [comment]
Zypper does use systemd-inhibit which should block normal users from rebooting. However systemd currently does not support blocking root from rebooting:

https://github.com/systemd/systemd/pull/9356
