### ISSUE TITLE
include purge-kernels-service

### ISSUE THREAD

**Issue by lnussel** [openSUSE/zypper#346]
purge-kernels-service is a package that contains only 313 byte service file that's only purpose is to call zypper. How do you feel about including that in the zypper sources and ship as  subpackage?

**Comment by mlandres** [comment]
Would this make a difference? Except that the package would always be rebuilt (and thus updated) together with zypper.

**Comment by lnussel** [comment]
To keep the multiversion stuff in one place as it only ever calls zypper anyways. I don't know whether we have any other package that ships only a single service file separately from the program it calls :-)

Also somewhat related to https://github.com/openSUSE/libzypp/pull/234

**Comment by mlandres** [comment]
Still No. The script calls whatever the kernel guys think is appropriate when removing their stuff. We offered help on removing the packages, to prevent them from further violating user locks, but that's all. They define what the script has to do and not zypper.
Later, when zypp supports it, the package can host the config snippets and whatever else the distro needs as well. But it's IMO no subpackage that has to be built with zypper.

**Comment by mlandres** [comment]
CLosing it. purge-kernels-service is shippred as a standalone package.
