### ISSUE TITLE
zypper se —provides-pkg

### ISSUE THREAD

**Issue by marguerite** [openSUSE/zypper#381]
Hi 

I would like to know how “zypper se —provides” works because I found it is ambiguous for translation.

I read the terms, it said “search all packages that provides any of the provides of the packages matched by the input parameter”. I think it means if I “zypper se —provides-pkg nginx”, zypper will do the following jobs:

1. find nginx package (“matched by input parameter”
2. find the rpm Provides of nginx (“the provides of”)
3. find packages whose rpm Provides containing a string that matches any of the Provides in step 2. (“provides the Provides”)

But after the test I got search results that I can’t understand. even “xz” is in the list.

The provides of xz (rpm -q —provides xz):

    lzma = 5.2.5
    xz = 5.2.5-1.16
    xz(x86-64) = 5.2.5-1.16

The provides of nginx (rpm -q --provides nginx):

    config(nginx) = 1.19.5-1.2
    http_daemon
    httpd
    nginx = 1.19.5-1.2
    nginx(x86-64) = 1.19.5-1.2
    perl(nginx) = 1.19.5
    user(nginx)

They got nothing in common, so how xz provides any of the provides of nginx?

**Comment by shenlebantongying** [comment]
I genuinely don't see the `xz` from both `zypper se --provides-pkg nginx` and `zypper se --provides-pkg nginx` in my machine (tw).

![image](https://user-images.githubusercontent.com/20123683/110230122-aa4cd900-7edc-11eb-8c6d-73348ca7dd4c.png)
---
![image](https://user-images.githubusercontent.com/20123683/110230228-84740400-7edd-11eb-896d-18b1cd6711d6.png)

**Comment by mlandres** [comment]
@marguerite I'd descrilbe it like this:
    
`--(provides|requires|recommends|supplements|conflicts|obsoletes|suggests) DEPENDENCY`

Returns back the packages which have `DEPENDENCY` in their (provides|requires...).
    
`-(provides|requires|recommends|supplements|conflicts|obsoletes|suggests)-pkg PACKAGE`

Returns back the packages which (provide|require...) the specified `PACKAGE`. This includes not only dependencies referring to PACKAGEs name but also to dependencies provided by PACKAGE.


Thus --provides-pkg is not the best example to understand those *reverse commands*. Its mostly there for comleteness. More common is probably --requires-pkg, which returns all package requiring the ones you specified.

**Comment by bzeller** [comment]
If you want to make sure that zypper really does what you want it to do, first run a normal zypper search to see what
input packages are used for the second query:

```zypper se nginx```

You will see that this matches a lot of packages, all of them would be in the input dataset for the reverse search:

```
S  | Name                                               | Summary                                                                         | Type
---+----------------------------------------------------+---------------------------------------------------------------------------------+-----------
   | dehydrated-nginx                                   | Nginx Integration for dehydrated                                                | package
   | fcgiwrap-nginx                                     | System services for using fcgiwrap with nginx                                   | package
i+ | nginx                                              | A HTTP server and IMAP/POP3 proxy server                                        | package
   | nginx                                              | A HTTP server and IMAP/POP3 proxy server                                        | srcpackage
   | nginx-debuginfo                                    | Debug information for package nginx                                             | package
   | nginx-debugsource                                  | Debug sources for package nginx                                                 | package
   | nginx-geolite-asn                                  | IP ASN geolocation databases for nginx                                          | package
   | nginx-geolite-asn                                  | IP ASN geolocation databases for nginx                                          | srcpackage
   | nginx-geolite-city                                 | Free IP city geolocation databases for nginx                                    | package
   | nginx-geolite-city                                 | Free IP city geolocation databases for nginx                                    | srcpackage
   | nginx-geolite-country                              | Free IP country geolocation databases for nginx                                 | package
   | nginx-geolite-country                              | Free IP country geolocation databases for nginx                                 | srcpackage
   | nginx-ingress-controller                           | Kubernetes ingress controller for nginx                                         | package
   | nginx-ingress-controller                           | Kubernetes ingress controller for nginx                                         | srcpackage
   | nginx-ingress-controller-debuginfo                 | Debug information for package nginx-ingress-controller                          | package
   | nginx-module-brotli                                | NGINX module for Brotli compression                                             | package
   | nginx-module-brotli                                | NGINX module for Brotli compression                                             | srcpackage
........ And more 
```
So if you want only nginx you need:
```
# input data
zypper se --match-exact nginx

#full search 
zypper se --match-exact --provides-pkg nginx
```
So what I usually do for those types of searches, I first tweak the basic query and once I'm ready with that input set I add the `--(provides|requires|recommends|supplements|conflicts|obsoletes|suggests)-pkg` switches.
