### ISSUE TITLE
[Feature request] Add comment to package lock

### ISSUE THREAD

**Issue by cbcoutinho** [openSUSE/zypper#388]
Hi,

I have disabled a third-party package as it unnecessarily conflicts with an openSUSE package by using `zypper addlock`. To make this easier to understand for others on the system, I would like to add a comment to the lock, similar to how repositories can have aliases.

I was hoping for something like this:

```shell
$ sudo zypper addlock -r bad-repo --comment "Conflicts with packageA in good-repo" packageB
```

**Comment by mlandres** [comment]
A good idea.

**Comment by mlandres** [comment]
zypper 1.14.48 will support addlock *-m, --comment* to add a comment when specifying a lock.
Thanks to @coolgw who implemented it.
