### ISSUE TITLE
Cmake cannot locate Zypper Common. 

### ISSUE THREAD

**Issue by supreetsingh10** [openSUSE/zypper#389]
I want to contribute to zypper, I cloned this directory and I did ```cmake  .``` in the directory. I am getting this error

        
        CMake Error at CMakeLists.txt:11 (INCLUDE):
       INCLUDE could not find requested file:

       ZyppCommon

    CMake Error at CMakeLists.txt:38 (GENERATE_PACKAGING):
    Unknown CMake command "GENERATE_PACKAGING".

    -- Configuring incomplete, errors occurred!
    See also "/home/supreetsingh/OpenSource/zypper/CMakeFiles/CMakeOutput.log".

If I am making a mistake with this, I would like to apologize beforehand, I would appreciate help, I want to contribute to this project.

**Comment by mlandres** [comment]
@supreetsingh10 you need to install `libzypp-devel` (it's provided by [libzypp](https://github.com/openSUSE/libzypp/blob/master/cmake/modules/ZyppCommon.cmake))

**Comment by supreetsingh10** [comment]
Thank you so much sir! On it.
