### ISSUE TITLE
"..search --sort-by-name.." is case-insensitive

### ISSUE THREAD

**Issue by MrM40** [openSUSE/zypper#391]
zypper version 1.14.45 (current 15.3 stable)
I would expect the following command would output a sorted package-list but that's not the case:
`zypper search --sort-by-name wind` 

(I am aware --sort-by-name is default)

Result:
![packages](https://user-images.githubusercontent.com/16258063/121428162-c8abf000-c975-11eb-985f-ed279d68a65d.jpg)

**Comment by mlandres** [comment]
You mean, it should be sorted case-insensitive, right?

**Comment by MrM40** [comment]
Yea, I just noticed that it myself! 
Then I guess it's less important / low priority.
