### ISSUE TITLE
Reorder display for Updates

### ISSUE THREAD

**Issue by stoecker** [openSUSE/zypper#403]
When doing a "zypper dup" there is output
* The following 288 NEW packages are going to be installed:
* The following 76 packages are going to be REMOVED:
* The following 5878 packages are going to be upgraded:
* The following 26 patterns are going to be upgraded:
* The following product is going to be upgraded:
* The following 2 packages are going to be downgraded:
* The following 4 packages are going to be reinstalled:
* The following package is going to change architecture:
* The following 5 packages require a system reboot:

As you already can see on the numbers the majority is upgrade. But the "REMOVED" actually is the most important to know, which you only see after scrolling up (which is not always possible by the way). Please simply change the order:
* 1) package/patterns/product upgraded (now 3-5)
* 2) NEW (now 1)
* 3) REMOVED (now 2)

This way the most important information is visible without scrolling at the end.

**Comment by mlandres** [comment]
fixed for zypper-1.14.48
