### ISSUE TITLE
 Spelling error in: zypper lifecycle --help output

### ISSUE THREAD

**Issue by tbazant** [openSUSE/zypper#449]
There is a spelling error in: zypper lifecycle --help output

command: sudo zypper lifecycle --help

original output line: --diff <file> Report only differences from previouly saved report

previouly -> previously

**Comment by mlandres** [comment]
I'll forward it to the maintainer.

**Comment by mlandres** [comment]
Tracked in [bug#1201960](https://bugzilla.suse.com/show_bug.cgi?id=1201960).
