### ISSUE TITLE
No reference to the 'lifecycle' subcommand of zypper in the man page

### ISSUE THREAD

**Issue by tbazant** [openSUSE/zypper#450]
There is no reference to the lifecycle subcommand of zypper in the man page.

**Comment by mlandres** [comment]
'_Plugins_' AKA ' _subcommands_' can not be mentioned in the man page. They are usually not maintained by us, so we don't know what exists and what is actually installed on a system. The man page explains the `subcommand` command, which explores the system.

`zypper subcommand` lists the subcommands actually found on the system:
```
Available zypper subcommands in '/usr/lib/zypper/commands':

      lifecycle             products and packages lifecycle information
```

`zypper help _SUBCOMMAND_`  (e.g. `zypper help lifecycle` ) shows the subcommands man page, if it provides on.

`zypper lifecycle _ARGS_` (e.g. `zypper lifecycle --help`) calls the plugin and forwards the _ARGS_ to it.
