### ISSUE TITLE
Explain outdatedness of repos

### ISSUE THREAD

**Issue by jengelh** [openSUSE/zypper#463]
![Image Pasted at 2022-11-3 11-42](https://user-images.githubusercontent.com/8861948/199717717-681ed281-c568-442b-9d20-48923ba18863.jpeg)

Please have zypper explain how it came to the conclusion that a repo is outdated. In libzypp there seems to be a repositoryExpire attribute, but how is this filled and why.

**Comment by mlandres** [comment]
The repository metadata may define a TTL.
```
<suseinfo xmlns="http://linux.duke.edu/metadata/repo">
  <expire>2592000</expire>
</suseinfo>
```
 Repos doing this promise to regenerate their metadata within the specified interval. If they don't, you may be connected to a broken mirror or the repo is discontinued.

Maybe we can rephrase the message.
