### ISSUE TITLE
List dependency seperately  when package NAME is supplied with *

### ISSUE THREAD

**Issue by esdnm** [openSUSE/zypper#477]
Hi, I have been using OT for a few days, one thing i have noticed that, when i wanted to uninstall a few packages (all of `xfce-*)` `zypper` listed all of the package with `xfce-` at the start of their name along with their libraries in one single list. It would be nice if this two things were listed separately, like first all the package i told to remove and then all the package that will also be removed for that action. After that there could be a list off all the packages that will get removed on that run.

(P.S.: This may apply for package installation, but I haven't been able to test that yet.)

**Comment by mlandres** [comment]
That's something the verbose mode does. It explains into what the commandline arguments translate.
```
# zypper -v rm 'te*'
Verbosity: 2
Non-option program arguments: 'te*' 
Initializing Target
Reading installed packages...
Selecting 'telnet-1.2-lp152.3.6.x86_64' for removal.
Selecting 'terminfo-6.1-lp152.7.67.x86_64' for removal.
Selecting 'terminfo-base-6.1-lp152.7.67.x86_64' for removal.
Selecting 'terminfo-iterm-6.1-lp152.7.67.x86_64' for removal.
Selecting 'terminfo-screen-6.1-lp152.7.67.x86_64' for removal.
Selecting 'texlive-lm-fonts-2017.137.2.004svn28119-lp152.8.2.noarch' for removal.
Warning: 'texlive-lm-fonts' is locked. Use 'zypper removelock texlive-lm-fonts' to unlock it.
Resolving package dependencies...
...
```

**Comment by esdnm** [comment]
Closing since I have moved to Fedora Workstation again
