### ISSUE TITLE
Unable to install protonmail bridge due to missing dependencies

### ISSUE THREAD

**Issue by Sylvain-27** [openSUSE/zypper#482]
Hello,

I want to install protonmail bridge to interface with thunderbird, but I am unable to install the protonmail bridge rpm because it lacks dependencies not available with zypper.
When I type:

rpm -ivh protonmail-bridge-3.0.19-1.x86_64.rpm

attention: protonmail-bridge-3.0.19-1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e6234b07: NOKEY
error: Required dependencies:
         dejavu-sans-fonts is needed for protonmail-bridge-3.0.19-1.x86_64
         libEGL is needed for protonmail-bridge-3.0.19-1.x86_64
         libgcc is needed for protonmail-bridge-3.0.19-1.x86_64
         libglvnd-glx is needed for protonmail-bridge-3.0.19-1.x86_64
         libstdc++ is required for protonmail-bridge-3.0.19-1.x86_64
         libxkbcommon-x11 is needed for protonmail-bridge-3.0.19-1.x86_64

Why are dependencies not available in repositories?

Protonmail bridge is not available with zypper.

Especially since protonmail bridge is becoming common for users. It's unfortunate.

Thank you for your help.

**Comment by mlandres** [comment]
If you type `rpm -ivh protonmail-bridge-3.0.19-1.x86_64.rpm` you are using `rpm` not zypper. rpm does not know anything about repositories. It just sees what's offered on the comandline. 
Try `zypper in protonmail-bridge-3.0.19-1.x86_64.rpm`

**Comment by mlandres** [comment]
> Protonmail bridge is not available with zypper

zypper depends on the repositories you have added and enabled on your system (see them with `zypper lr). They advertise the rpm package zypper is able to download and install.

If `protonmail-bridge` is not advertised in your repos you may manually download and install the package (see above). If  you find a repository that offers protonmail-bridge for your distribution, you can add it (see `zypper ar ...`) and to install the package by name (`zypper in protonmail-bridge`). You can visit e.g. https://software.opensuse.org/  or https://build.opensuse.org/ to search for packages in distribution or user repositories.

Zypper uses repositories, but has no influence on their content. If you think protonmail-bridge should be added to the distribution you are using, you should raise the topic e.g. on the distributions mailinglist.
