### ISSUE TITLE
KDE "get new"

### ISSUE THREAD

**Issue by Acharab** [openSUSE/zypper#541]
I just installed a fresh install of tumbleweed, and there is an issue with Kde plasma. When I go to global themes and choose any "get new" button, nothing happens. I read that some people experienced the same issue on reddit

**Comment by mlandres** [comment]
@Acharab frankly, I don't know what these _global themes_ "_get new_" buttons are and how they work. This may be part of some desktop application, but it's not maintained by us.
 
I'd suggest to open a [bugreport for Tumbleweed](https://bugzilla.suse.com/enter_bug.cgi?product=openSUSE%20Tumbleweed). Chose `KDE Workspace (plasma)` as component. If you have further information or links to discussions, you can add them there. It may help the KDE guys to hunt this bug.
