### ISSUE TITLE
zypper returned 104 with 'No provider of 'sle-module-basesystem' found.'

### ISSUE THREAD

**Issue by bhat-anusha** [openSUSE/zypper#561]
I have a rmt server which has following products enabled. 
![image](https://github.com/user-attachments/assets/4949147d-c27f-4394-b7e6-3b285aa596e1)

When my client tries to register with rmt-server, it fails with error for all the products. Even with SUSEConnect, getting same error. Also, we are getting this error for all Products. 
![image](https://github.com/user-attachments/assets/e1ca9590-f776-4b06-a9dd-8e84aee47b82)

when debug log enabled, following is the error log 
![image](https://github.com/user-attachments/assets/13a9c4fc-a303-4354-a375-208124996aea)

Can anyone please tell me if I have missed anything.

**Comment by mlandres** [comment]
Sorry @bhat-anusha but I don't know enough about rmt to help you.

The error `104 - ZYPPER_EXIT_INF_CAP_NOT_FOUND` simply means that the requested item for the install command (i.e. product:sle-module-basesystem) is not available in any of the enabled repositories. The question however is _why_?

Before the install command you see the service `Basesystem_Module_x86_64` being added. The service provides you 2 repositories (`SLE-Module-Basesystem15-SP5-Updates` and `-Pool`). But the repos do not contain a `product:sle-module-basesystem` to install (or `-t product sle-module-basesystem`).

Maybe rmt inappropriately uses the `--no-refresh` switch to prevent zypp from checking whether the local repo metadata are up-to-date. Maybe the repositories do not provide enough content - or the service does not provide you enough repositories. That's something the RMT maintainers should be able to answer.

I'd suggest to open a bugreport at [bugzilla.suse.com](https://bugzilla.suse.com/enter_bug.cgi?product=SUSE%20Linux%20Enterprise%20Server%2015%20SP5) for component `RMT`. After such a failed attempt you can capture the `/var/log/zypper.log` and attach it to the bugreport. Maybe it provides some more details.
