### ISSUE TITLE
Distinguish package lock variants better

### ISSUE THREAD

**Issue by elfring** [openSUSE/zypper#574]
I marked a few packages by the application “YaST2 sw_single”.
* Taboo ‒ Never install
* Protected ‒ Do not modify

Should such information be also distinguishable in the list which can be presented by the command “zypper locks”? :thinking:

**Comment by mlandres** [comment]
This is an artificial distinction YAST makes. They use different names depending on whether the package is installed or not. Technically it's the same kind of lock. In `zypper ll -s` they are tagged `Keep installed` and `Do not install`.
