### ISSUE TITLE
Zypper homepage (`en.opensuse.org`) - Error 502: Bad Gateway

### ISSUE THREAD

**Issue by kdeldycke** [openSUSE/zypper#577]
Zypper homepage at https://en.opensuse.org/Portal:Zypper is returning an error 502:

<img width="524" alt="Screenshot 2024-11-11 at 11 20 05" src="https://github.com/user-attachments/assets/f1910e65-50a6-45cf-afac-f47811168b6d">

```
Bad Gateway!

The proxy server received an invalid response from an upstream server.

The proxy server could not handle the request

Reason: DNS lookup failure for: atlas-login.infra.opensuse.org

If you think this is a server error, please contact the [webmaster](mailto:admin@opensuse.org).

Error 502

en.opensuse.org
Apache
```

**Comment by mlandres** [comment]
That's in fact an issue of  the opensuse.org servers, not zypper. For me the pages there work (again?). If they don't work for you, please send a mail to  webmaster / admin@opensuse.org. Thanks.

**Comment by kdeldycke** [comment]
I can confirm it is now fixed on my side! :)
