### ISSUE TITLE
Set the default value of the zypper interaction operation to "n"

### ISSUE THREAD

**Issue by fxzxmic** [openSUSE/zypper#582]
I've had more than one occasion where I've mistakenly hit the enter key and ended up doing an action I didn't want to do.

**Comment by fxzxmic** [comment]
dnf is "n" by default, but a single parameter can change it.
```
--assumeyes                     (automatically answer yes for all questions)
--assumeno                      (automatically answer no for all questions)
```
@Floetenschlumpf Can you explain what you're not happy with?

**Comment by mlandres** [comment]
You can use `--dry-run` to prevent changes. But we won't change a 20 years old default on behalf of a single request.

**Comment by mlandres** [comment]
Feel free to provide a PR introducing a zypper.conf option to customize the install prompt's default. With this they could change their default.

**Comment by fxzxmic** [comment]
`--dry-run` doesn't fit because I'm not sure if I want to perform the operation until I get the output from zypper.
