### ISSUE TITLE
$releasever and $basearch not supported in .repo files

### ISSUE THREAD

**Issue by KAMiKAZOW** [openSUSE/zypper#63]
Not sure if it belongs to libzypp or here.
Just for fun I installed zypper on my Fedora system.
While in general in seems to work, its practical use is limited because in Fedora's repo files the URLs contain the two variables $releasever and $basearch, i.e. http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/$basearch/ translates into http://download.fedoraproject.org/pub/fedora/linux/updates/21/x86_64/ on a 64bit Fedora 21 installation.

IMO that change would also be beneficial for openSUSE because one thing that regularly annoys me is that after an upgrade I have to tweak all my repos to match the new version number. If I could just add the repo URL http://download.opensuse.org/repositories/home:/KAMiKAZOW/openSUSE_$releasever/ and it'll survive all my oS distro upgrades, it would be great.

**Comment by mlandres** [comment]
```
$ cat /etc/zypp/repos.d/openSUSE:repo-non-oss.repo
[openSUSE:repo-non-oss]
name=repo-non-oss ($releasever)
enabled=1
autorefresh=1
baseurl=http://download.opensuse.org/distribution/$releasever/repo/non-oss
type=yast2
service=openSUSE
```
We support this for quite a long time. If your zypper isn't too old (before 2010), at least $basearch should work. May of course be the detection of $releasever on RHEL/Fedora systems has changed.

We're looking for the version of the 1st package providing 'redhat-release'. If the rules have changed, let me know and I'll try to fix it.

**Comment by KAMiKAZOW** [comment]
I use zypper 1.11.23 as packaged at https://build.opensuse.org/package/show/devel:cloverleaf:testing/zypper
redhat-release is provided by fedora-release and its version number is correct.

Still zypper complains about wrong URLs. Any hints what I could try or look into?

**Comment by mlandres** [comment]
```zypper lr -u``` shows the expanded URL, so if this is wrong something broke. Logfile is 
```/var/log/zypper.log```, in case of doubt  send it to me (ma@suse.de) and I'll have a look at it.

**Comment by KAMiKAZOW** [comment]
zypper lr -u looks just fine. It seems that there is some issue with retrieving the GPG keys for signing but I'm not sure.

I'm sending you the log right away.

**Comment by mlandres** [comment]
```
2015-04-10 20:32:37 <3> ronny.linux(11246) [zypp] RepoFileReader.cc(repositories_in_stream):145 
Unknown attribute in [fedora]: metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
ignored
```
This seems to be the problem. Zypper does not know the 'metalink=' tag. This would be easy to fix.

Try renaming it to ```mirrorlist=```. If a metalink file is returned, zypper should detect and parse it. This way it worked for me.

**Comment by KAMiKAZOW** [comment]
Works better but not fully:
Error building the cache:
Url scheme is a required component                                                                          
Warning: Skipping repository 'RPM Fusion for Fedora 21 - Free' because of the above error.

**Comment by mlandres** [comment]
```:(``` The mirrorlist parser does not ignore '#'-comment lines.
There's no workaround for this. You'll need the latest libzypp (https://github.com/openSUSE/libzypp/commit/7465363386769ad04bfb503f02dcf4d1982bba1c). It hopefully fixes also the  ```metalink=``` issue.

**Comment by KAMiKAZOW** [comment]
Oh, great…
Now zypper gives me "Error building the cache: Parse Error" and yum complains about Metalink files not being XML…

**Comment by KAMiKAZOW** [comment]
No idea why all that messed with yum. Now I had to rename every "metalink" to "mirrorlist" again or yum bitches. Haha.
Everything (yum, dnf, zypper) seems to work now. Thanks a lot for your effort.
