### ISSUE TITLE
man section zypper download 

### ISSUE THREAD

**Issue by vmoutoussamy** [openSUSE/zypper#68]
"download
              Download rpms specified on the commandline to a local directory.
              Per  default  packages are downloaded to the libzypp package cache (/var/cache/zypp/packages; for non-root users $XDG_CACHE_HOME/zypp/packages), but this
              can be changed by using the global --pkg-cache-dir option.

              In XML output a <download-result> node is written for each package zypper tried to downlad. Upon  success  the  local  path  is  is  found  in  download-result/localpath@path."

The next to last and last sentence are clearly bad written... excluding the typo.
I did understand that when using "zypper -x download" you will have a "\<download-result\>"node per package zypper tried to download upon success or failure in the XML output, but I think this sentence could be more clear. But I still don't understand the last sentence, could someone improved this last sentence please ?.

Thanks,

**Comment by mlandres** [comment]
I tried:
```
Parsable XML-output produced by 'zypper --xmlout' will include a <download-result> node
for each package zypper tried to download. Upon success the location of the downloaded
package is found in the 'path' attribute of the <localfile> subnode 
(xpath: download-result/localpath@path*).

	<download-result>
	  <solvable>
	    <kind>package</kind>
	    <name>zypper</name>
	    <edition epoch="0" version="1.9.17" release="26.1"/>
	    <arch>x86_64</arch>
	    <repository name="repo-oss-update (13.1)" alias="openSUSE:repo-oss-update"/>
	  </solvable>
	  <localfile path="/var/cache/zypp/packages/openSUSE:repo-oss-update/x86_64/zypper-1.9.17-26.1.x86_64.rpm"/>
	</download-result>
```

**Comment by vmoutoussamy** [comment]
Hi,
Thanks a lot mlandres for your quick response and your modification !!
Regards,
