### ISSUE TITLE
Always ignore unsigned 'repomd.xml' files 

### ISSUE THREAD

**Issue by KAMiKAZOW** [openSUSE/zypper#70]
Fedora's 'repomd.xml' files are always unsigned. Yeah, I know: Not so great.
However zypper always asks "unsigned, continue? [yes/no] (no)".
Could you implement a "Don't ask for this repo again" / "Always yes" answer, please? I guess it's fine when it asks the first time but every time is very tedious.

**Comment by mlandres** [comment]
Yes, we'll address this in one of the next versions.

**Comment by mlandres** [comment]
zypper-1.12.2 (libzypp-15.3.0) should accept unsigned repos if the package gpg check is not disabled. I guess this resolves your issue?

**Comment by alogoc** [comment]
Have the same issue with zypper-1.6.326-0.7.2 while automating some tasks.

Since zypper does not offer a "yes" switch for that, the only way for me to move forward was with "--no-gpgcheck" switch, which is not very good.

I hope this was addressed properly on future versions.
