### ISSUE TITLE
[feature request] zypper groups on fedora

### ISSUE THREAD

**Issue by damianatorrpm** [openSUSE/zypper#76]
Zypper should be able to handle groups in Fedora maybe?

```
[root@fed22 ~]# zypper install -t pattern core
Loading repository data...
Reading installed packages...
'core' not found in package names. Trying capabilities.
No provider of 'core' found.
Resolving package dependencies...

Nothing to do.
```

```
[root@fed22 ~]# zypper install -t pattern @core
Loading repository data...
Reading installed packages...
'@core' not found in package names. Trying capabilities.
No provider of '@core' found.
Resolving package dependencies...

Nothing to do.
```

```
[root@fed22 ~]# zypper install @core
Loading repository data...
Reading installed packages...
'@core' not found in package names. Trying capabilities.
No provider of '@core' found.
Resolving package dependencies...

Nothing to do.
```

```
[tux@fedora ~]$ dnf group info core
Last metadata expiration check performed 0:05:30 ago on Tue Jul 14 11:09:41 2015.

Group: Core
 Description: Smallest possible installation
 Mandatory Packages:
   audit
   basesystem
   bash
   coreutils
   cronie
   curl
   dhcp-client
   dnf
   dnf-yum
   e2fsprogs
   filesystem
   glibc
   grubby
   hostname
   initscripts
   iproute
   iputils
   kbd
   less
   man-db
   ncurses
   openssh-clients
   openssh-server
   parted
   passwd
   plymouth
   policycoreutils
   procps-ng
   rootfiles
   rpm
   selinux-policy-targeted
   setup
   shadow-utils
   sudo
   systemd
   uboot-tools
   util-linux
   vim-minimal
 Default Packages:
   NetworkManager
   authconfig
   dnf-plugins-core
   dracut-config-rescue
   firewalld
   ppc64-utils
```

**Comment by mlandres** [comment]
Need to investigate how far this is already integrated into https://github.com/openSUSE/libsolv.

**Comment by damianatorrpm** [comment]
The groups in Fedora are called comps and they are actually contained in a file in the repodata directory of a repository. In openSUSE for groups there are metapackage, i.e rpm packages that depend on other packages.
http://ftp.halifax.rwth-aachen.de/fedora/linux/releases/22/Everything/x86_64/os/repodata/

In case someone stumbles across here and didn't know.

**Comment by Conan-Kudo** [comment]
@mlandres From the last time I talked to @mlschroe about it, it's not a very complete implementation, but I could be wrong. If libsolv's comps capabilities aren't sufficient, there's [libcomps](https://github.com/rpm-software-management/libcomps) as an option. DNF currently uses that for providing comps support.

**Comment by mlandres** [comment]
@Conan-Kudo Thanks for the link. Nevertheless zypper will require this to be supported by [libsolv](https://github.com/openSUSE/libsolv).

**Comment by Conan-Kudo** [comment]
@mlandres I asked @mlschroe about comps support in libsolv, and he noted that libsolv has a "simple parser to have the group information available."

So it might actually be at a point where you could start using it. But of course, you should talk to him more about it.

**Comment by Conan-Kudo** [comment]
@mlandres Is there a chance this could get in soon? I've been fiddling with Zypper on Fedora with the intent to package it and provide it as an option, but I'd like to see at least basic support for comps groups before submitting it for inclusion in Fedora.

**Comment by mlandres** [comment]
> Is there a chance this could get in soon? 

Sorry, but 'no'. There's currently neither priority nor resource for this.

**Comment by Conan-Kudo** [comment]
@mlandres A small update: Fedora no longer uses the comps data for languages (it has moved to using rich dependencies, which works with libsolv now), so the support in libsolv is now sufficient for using Fedora's comps data.

**Comment by bzeller** [comment]
Since comps are no longer used on Fedora we can close this bug.

**Comment by Conan-Kudo** [comment]
@bzeller What the hell are you talking about? comps are still actively used. We just don't use them for langpack selection anymore.

**Comment by Conan-Kudo** [comment]
Composition groups are still actively maintained and merged into Fedora releases from here: https://pagure.io/fedora-comps
