### ISSUE TITLE
Zypper displaying incorrectly with CJK/double width characters

### ISSUE THREAD

**Issue by MingcongBai** [openSUSE/zypper#90]
Zypper is not displaying correctly when using CJK locales or anything that uses double width characters, the lines are actually displaying over a line's width that a terminal emulator contains.

It might be confusing in my language, well here is a screenshot of what is happening on my screeen.

![screenshot_20151231_111709](https://cloud.githubusercontent.com/assets/5006263/12067043/0da397f2-afb0-11e5-9458-c317b28008fc.png)

If you look to the right of a line, the speed indicator is actually displaying on the next line...

Versions of Zypper runtime:

- `zypper` version 1.12.27
- `libzypp` version 15.19.7

This is not openSUSE, it is another distribution with RPM as package manager with Zypper as the default admin utility.

**Comment by MingcongBai** [comment]
And here when I am installing packages...

![screenshot_20151231_112426](https://cloud.githubusercontent.com/assets/5006263/12067106/1c4f191a-afb1-11e5-993b-f70e0b951b33.png)

**Comment by mlandres** [comment]
I can't reproduce this. With `LANG=zh_CN.UTF-8` my xterm as well as the linux console show correct line length.

Zypper uses `wcwidth(3)` to determine the columns needed to display a wide character. This system call depends on the LC_CTYPE category of the current locale. You can use the `locale` command to check the settings in use. The output looks as if LC_MESSAGES uses a CJK locale but LC_CTYPE does not.
