### ISSUE TITLE
Wrong German translation: "has source package" -> "enthält Quellpaket"

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/zypper#95]
When running ```zypper si```:

> Package 'yast2-qt-branding-openSUSE' has source package 'branding-openSUSE'.

gets translated to

> Das Paket 'yast2-qt-branding-openSUSE' enthält das Quellpaket 'branding-openSUSE'.

That is the wrong way around. Better would be:

> Das Paket 'yast2-qt-branding-openSUSE' ist im Quellpaket 'branding-openSUSE' enthalten.

**Comment by mlandres** [comment]
AFAIK this is already fixed for the next version. It now reads
> ...hat das Quellpaket..
