### ISSUE TITLE
Wildcards do not work with a dash (-) in front

### ISSUE THREAD

**Issue by diegit** [openSUSE/zypper#97]
Hi,
I tried to install all texlive fonts at once and run into problems with zypper and wild cards. The names of the packages are comparable to  "texlive-universalis-fonts".

With zypper install 'texlive-*fonts':
Paket 'texlive-*-fonts' nicht gefunden. (no packages found)

with zypper install 'texlive*fonts' or  zypper install 'texlive*-fonts' :
 >200 packages found

So zypper install does not find any packages, if there's a dash in front of the wild card.

This problem does not occur when I search for packages:
zypper se 'texlive-*-fonts' | wc -l
256

zypper se 'texlive*fonts' | wc -l
271

I'm on Tumbleweed with  zypper 1.13.4.
thank you!

**Comment by mlandres** [comment]
Thanks!

**Comment by mlandres** [comment]
Fixed for libzypp-16.2.5
